### ISSUE TITLE
I hope can cout a lot of md file in folder

### ISSUE THREAD

**Issue by recursionBlack** [gandreadis/markdown-word-count#19] opened 2024-04-12 02:08 UTC

**Comment by cariad** [comment] 2024-04-12 06:28
Hi! Personally, I'd build something like that using the package rather than the CLI:

```python
from mwc.counter import count_words_in_markdown
from pathlib import Path

count = 0
directory = Path("my_markdown_files")

for file in directory.glob("*.md"):
    with open(file, "r") as f:
        body = " ".join(f.readlines())
        count += count_words_in_markdown(body)

print(count)
```

**Comment by gandreadis** [comment] 2024-04-15 07:58
Hi @cariad and @recursionXie. Thank you for submitting an issue. I don't yet fully understand the problem, however: the package can already currently be used like this. There is an API available, and the code @cariad shared is runnable with the package, as-is. Is there another issue I'm missing? Or would you like this usage mode more prominently documented?

**Comment by recursionBlack** [comment] 2024-04-15 08:24
I mean that I have many md file in a folder, folder also nest have folder, in this condition, I want to statistics every word frequence count in such folder.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gandreadis** [comment] 2024-04-15 08:27
Alright, but then this is a duplicate of #14 - this is an existing issue where we track support for that function.

**Closed as not planned by gandreadis** 2024-04-15 08:27 UTC
